DEBUG [2024-01-23 15:20:43] asyncio - Using selector: KqueueSelector
INFO [2024-01-23 15:20:43] root - Listening on port 8888
INFO [2024-01-23 15:20:47] root - Response from client 186e5699-2b1e-4c08-a1f6-76825ed69d69: {'client_id': '186e5699-2b1e-4c08-a1f6-76825ed69d69', 'name': 'Vidoosh', 'age': '70', 'industry': 'publiccvb', 'salary': 'INR50', 'city': 'Chennai'}
ERROR [2024-01-23 15:20:47] tornado.application - Uncaught exception POST / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 74, in post
    self.save_response(client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 107, in save_response
    client_database.insert_data(cur, client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 19, in insert_data
    cursor.execute("INSERT INTO client_details (client_id, data) VALUES (%s, %s)", (client_id, data))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3140, 'Invalid JSON text: "Missing a name for object member." at position 1 in value for column \'client_details.data\'.')
ERROR [2024-01-23 15:20:47] tornado.access - 500 POST / (::1) 5.62ms
INFO [2024-01-23 15:20:47] root - Response from client cbb39f8e-49f8-4235-9929-6c8f831ebc51: {'client_id': 'cbb39f8e-49f8-4235-9929-6c8f831ebc51', 'name': 'Vidoosh', 'age': '70', 'industry': 'publiccvb', 'salary': 'INR50', 'city': 'Chennai'}
ERROR [2024-01-23 15:20:47] tornado.application - Uncaught exception POST / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 74, in post
    self.save_response(client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 107, in save_response
    client_database.insert_data(cur, client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 19, in insert_data
    cursor.execute("INSERT INTO client_details (client_id, data) VALUES (%s, %s)", (client_id, data))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3140, 'Invalid JSON text: "Missing a name for object member." at position 1 in value for column \'client_details.data\'.')
ERROR [2024-01-23 15:20:47] tornado.access - 500 POST / (::1) 1.43ms
ERROR [2024-01-23 15:20:47] tornado.application - Uncaught exception GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 93, in get
    lookup = client_database.data_lookup(cur, c_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 26, in data_lookup
    cursor.execute(f"SELECT data from client_details WHERE client_id = {client_id}")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<html><title>500: Internal Server Error</title><body>500: Internal Server Error<' at line 1")
ERROR [2024-01-23 15:20:47] tornado.access - 500 GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1) 1.41ms
ERROR [2024-01-23 15:20:47] tornado.application - Uncaught exception GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 93, in get
    lookup = client_database.data_lookup(cur, c_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 26, in data_lookup
    cursor.execute(f"SELECT data from client_details WHERE client_id = {client_id}")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<html><title>500: Internal Server Error</title><body>500: Internal Server Error<' at line 1")
ERROR [2024-01-23 15:20:47] tornado.access - 500 GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1) 1.18ms
INFO [2024-01-23 15:22:36] root - Response from client cdf7ee57-cca0-420e-b8f4-96f645a8dc10: {'client_id': 'cdf7ee57-cca0-420e-b8f4-96f645a8dc10', 'name': 'Vidoosh', 'age': '70', 'industry': 'publiccvb', 'salary': 'INR50', 'city': 'Chennai'}
ERROR [2024-01-23 15:22:36] tornado.application - Uncaught exception POST / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 74, in post
    self.save_response(client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 107, in save_response
    client_database.insert_data(cur, client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 19, in insert_data
    cursor.execute("INSERT INTO client_details (client_id, data) VALUES (%s, %s)", (client_id, data))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3140, 'Invalid JSON text: "Missing a name for object member." at position 1 in value for column \'client_details.data\'.')
ERROR [2024-01-23 15:22:36] tornado.access - 500 POST / (::1) 2.50ms
INFO [2024-01-23 15:22:36] root - Response from client b550679b-69d8-4dcb-b32b-9a1299eb5337: {'client_id': 'b550679b-69d8-4dcb-b32b-9a1299eb5337', 'name': 'Vidoosh', 'age': '70', 'industry': 'publiccvb', 'salary': 'INR50', 'city': 'Chennai'}
ERROR [2024-01-23 15:22:36] tornado.application - Uncaught exception POST / (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 74, in post
    self.save_response(client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 107, in save_response
    client_database.insert_data(cur, client_id, response_data)
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 19, in insert_data
    cursor.execute("INSERT INTO client_details (client_id, data) VALUES (%s, %s)", (client_id, data))
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (3140, 'Invalid JSON text: "Missing a name for object member." at position 1 in value for column \'client_details.data\'.')
ERROR [2024-01-23 15:22:36] tornado.access - 500 POST / (::1) 1.64ms
ERROR [2024-01-23 15:22:36] tornado.application - Uncaught exception GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 93, in get
    lookup = client_database.data_lookup(cur, c_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 26, in data_lookup
    cursor.execute(f"SELECT data from client_details WHERE client_id = {client_id}")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<html><title>500: Internal Server Error</title><body>500: Internal Server Error<' at line 1")
ERROR [2024-01-23 15:22:36] tornado.access - 500 GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1) 1.39ms
ERROR [2024-01-23 15:22:36] tornado.application - Uncaught exception GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/server_2.py", line 93, in get
    lookup = client_database.data_lookup(cur, c_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vbang/test_folder/async_http_client_server/client_database.py", line 26, in data_lookup
    cursor.execute(f"SELECT data from client_details WHERE client_id = {client_id}")
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '<html><title>500: Internal Server Error</title><body>500: Internal Server Error<' at line 1")
ERROR [2024-01-23 15:22:36] tornado.access - 500 GET /?c_id=%3Chtml%3E%3Ctitle%3E500:%20Internal%20Server%20Error%3C/title%3E%3Cbody%3E500:%20Internal%20Server%20Error%3C/body%3E%3C/html%3E (::1) 1.11ms
